# Generated by Django 2.2.4 on 2019-08-24 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(verbose_name=' question date time')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lm_name', models.CharField(max_length=20)),
                ('subtitle', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=200)),
                ('paper_link', models.CharField(max_length=200)),
                ('rank', models.IntegerField(default=0)),
                ('loss', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(verbose_name=' answer date time')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatroom.Question')),
            ],
        ),
    ]
