# Generated by Django 2.2.4 on 2019-08-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_auto_20190819_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lm_name', models.CharField(max_length=20)),
            ],
        ),
    ]
